### ISSUE TITLE
How to unblend layers by HSV

### ISSUE THREAD

**Issue by 283pm** [yuki-koyama/unblending#5]
Hello.
Thank you for the great repository.

I am new to the program, and I have a question.
Is it possible to separate colors by inputting HSV values instead of separating images by RGB json input?

I think HSV is a more useful way to divide than RGB.

What part of the program should I change to make it work that way?

**Comment by setanarut** [comment]
HSV is not additive or subtractive color model unlike CMYK, RGB.
Here's how this repo works;
`input-image -> blending mode layers`
It has nothing to do with HSV.

**Comment by yuki-koyama** [comment]
Hi, thanks @283pm for the suggestion and @hazarek for the discussion! 

Yes, the blending works in the RGB color space, so in the algorithm level it has nothing to do with HSV. In the API level, it might be useful to support HSV and other color spaces, but to keep the simplicity I would like not to do so. If you want to use HSV, please write an independent script by yourself that converts HSV into RGB and then calls unblending.
